server:
  port: 9010

spring:
  application:
    name: ksport-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KillerLu/ksport/tree/master/ksport-base-module/ksport-config/config