server:
  port: 9010

spring:
  application:
    name: ksport-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KillerLu/spring-cloud-config.git
          search-paths: ksport